build:
  integration:
    image: morrisjobke/nextcloud-ci-php7:1.0.3
    commands:
      - git submodule update --init
      - ./occ maintenance:install --admin-pass=admin
      - cd build/integration
      - ./run.sh
  jsunit:
    image: morrisjobke/nextcloud-ci-jsunit:1.0.2
    commands:
      - ./autotest-js.sh
  sqlite:
    image: morrisjobke/nextcloud-ci-php7:1.0
    commands:
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
      - ./autotest.sh sqlite

compose:
  cache:
    image: redis
