language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:


matrix:
  allow_failures:
    - php: 7.0

env:
  global:
    - CURRENT_DIR=`pwd`
  matrix:
    - BACKEND=smbclient
    - BACKEND=libsmbclient

before_install:
  - pass=$(perl -e 'print crypt("test", "password")')
  - sudo useradd -m -p $pass test
  - sudo apt-get update -qq
  - sudo apt-get install samba smbclient
  - if [ "$BACKEND" == 'libsmbclient' ]; then ./install_libsmbclient.sh; fi
  - cd $CURRENT_DIR
  - chmod go+w $HOME
  - printf "%s\n%s\n" test test|sudo smbpasswd -s test
  - sudo mkdir /home/test/test
  - sudo chown test /home/test/test
  - |
    echo "[test]
    comment = test
    path = /home/test
    guest ok = yes
    writeable = yes
    map archive = yes
    map system = yes
    map hidden = yes
    create mask = 0777
    inherit permissions = yes" | sudo tee -a /etc/samba/smb.conf
  - sudo service smbd restart
  - testparm -s

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - cd tests
  - phpunit --coverage-clover ../build/logs/clover.xml --configuration phpunit.xml

after_script:
 - cd $CURRENT_DIR
 - php vendor/bin/coveralls -v
